canonical: http://hl7.org/fhir/uv/phd
fhirVersion: 6.0.0-ballot3  # Revert back to R6
id: hl7.fhir.uv.phd
name: PhdImplementationGuide
title: Personal Health Device Implementation Guide
status: active
language: en-US  
copyrightYear: 2016+
releaseLabel: STU 3 - R6  # Change back to R6
version: 3.0.0-draft
publisher:
  name: HL7 International / Health Care Devices
  url: http://www.hl7.org/Special/committees/healthcaredevices

# Extensions (IG-level metadata)
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: dev

# Jurisdiction
jurisdiction: urn:iso:std:iso:3166#001

dependencies:
  hl7.terminology.r5:
    version: 6.5.0
    reason: R6 terminology package not yet available
  hl7.fhir.uv.extensions.r5:
    version: 5.2.0
    reason: R6 extensions package not yet available
# Note: R6 terminology and extension packages are not yet available
# You'll get version mismatch warnings, but the build should still work

# Dependencies - Remove R5 dependencies since R6 packages don't exist yet
# Comment out or remove these until R6 versions are available:
# dependencies:
#   hl7.fhir.uv.pocd:
#     uri: http://hl7.org/fhir/uv/pocd/ImplementationGuide/hl7.fhir.uv.pocd
#     version: 0.3.0

# Special URLs
special-url:
  - http://terminology.hl7.org/CodeSystem/ASN1ToHL7
  - http://terminology.hl7.org/CodeSystem/ContinuaDeviceIdentifiers

# Resource descriptions and metadata
resources:
  # Code Systems
  CodeSystem/ContinuaDeviceIdentifiers:
    name: Continua Device Identifiers
    description: Codes that identify the device 'identifier', such as whether an EUI is a system id, Bluetooth address, or Ethernet MAC address
  
  CodeSystem/SimpleAlertOperationalStatesCS:
    name: SimpleAlertOperationalStates CodeSystem
  
  CodeSystem/ASN1ToHL7:
    name: ASN1 to HL7 Mapping
    description: Codes for the IEEE 11073-10206 BITs measurement bit values. For example, 150604.0 is the code for bit 0 in measurement type 150604 which is a pulse oximeter status. The description of that code is 'Indicates the device is not connected with the sensor'.
  
  # Value Sets
  ValueSet/ASN1MeasurementBits:
    name: ASN1 Measurement Bits
    description: Value set for those Asn1ToHL7 codes whose source is a measurement attribute.
  
  ValueSet/DeviceTypes11073MDC:
    name: Device Type Specialization IEEE 11073-10101 Nomenclature Codes
  
  ValueSet/SimpleAlertOperationalStates:
    name: Simple Alert Operational States Value Set
  
  ValueSet/MDCobject:
    name: IEEE 11073 MDC Object infrastructure and Device nomenclature
  
  # Capability Statement
  CapabilityStatement/PhdFHIRServer:
    name: PhdFHIRServer
  
  # Example Bundles
  Bundle/bundle-example-1:
    name: First time Bundle upload
    description: This example shows a full first time transaction Bundle containing Patient, Device, and Observation resources.
  
  Bundle/bundle-continuousnonin:
    name: Pulse Oximeter Bundle upload
    description: This example is an upload from a Bluetooth Low Energy Pulse oximeter device streaming data. In this case the gateway has previously uploaded measurements and saved the logical ids of the Patient and Device resources so they are not re-uploaded.
  
  # Example Devices
  Device/phd-74E8FFFEFF051C00.001C05FFE874:
    name: PHD Device Example
    description: This example PHD Device resource is referenced by other examples and is present for the validator.
  
  Device/phd-711000FEFF5F49B0.B0495F001071:
    name: Blood Pressure PHD
    description: This example maps the System Information data from a Blood Pressure PHD. This device did not report Reg-Cert-Data-List information.
  
  Device/phd-00601900010E9234.F45EABA80832:
    name: Glucose Monitor PHD
    description: This example maps an Glucose monitor PHD. It is referenced by a coded Glucose meal context observation
  
  Device/phg-ecde3d4e58532d31.000000000000:
    name: Gateway 1
    description: This example maps an Android Gateway
  
  Device/phg-example:
    name: Gateway 2
    description: This example maps an Android Gateway
  
  # Example DeviceMetric
  DeviceMetric/bp-devicemetric-example:
    name: Phd Device Metric for Blood Pressure 
    description: This example is a PhdDeviceMetric for a Blood Pressure measurement.
  
  # Example Patients
  Patient/patientExample-1:
    name: Known Patient 1
    description: This example maps a known patient where an optional patient name is included.
  
  Patient/patientExample-2:
    name: Unknown Patient
    description: This example maps an unknown patient.
  
  # Example Observations
  Observation/numeric-spotnumeric:
    name: Pulse rate numeric observation
    description: This example is a simple numeric observation of a pulse rate from a pulse oximeter. This particular example also has a component as the original measurement has a Supplemental Information attribute indicating that this is a SPOT measurement (a stable average).
  
  Observation/numeric-spo2-alarm:
    name: Pulse oximeter SpO2 observation with alert
    description: This example is a simple numeric observation from a pulse oximeter with an alert.
  
  Observation/temperature-observation:
    name: Body temperature observation
    description: This example is a simple numeric observation of a health thermometer.
  
  Observation/glucose-observation:
    name: Blood glucose observation.
    description: This example is a simple numeric observation of a (continuous) glucose monitor.
  
  Observation/numeric-observation-not-a-number:
    name: Observation with NaN measurement
    description: This example contains a NaN (not a number) measurement.
  
  Observation/rtsa-example:
    name: Pleth waveform observation
    description: This example is an RTSA observation of a pleth signal from a pulse oximeter. This very short waveform maps to a valueSampledData element.
  
  Observation/rtsa-example-2:
    name: ECG waveform with scaling
    description: This example is an RTSA observation of an ECG waveform with scaling.
  
  Observation/meal-context-observation:
    name: Meal context coded enumeration observation
    description: This example contains measurement that is itself a code. The measurement indicates that the glucose measurement was taken after lunch or dinner, also known as the meal context.
  
  Observation/bits-observation:
    name: ASN1 BITs measurement from a Pulse Oximeter
    description: This example is a device and sensor status measurement from a pulse oximeter.
  
  Observation/bpm-status:
    name: BPM status report
    description: This example reports the status of a BPM measurement.
  
  Observation/compound-numeric-blood-pressure:
    name: Blood pressure compound (numeric) observation
    description: This example reports a measurement from a Blood Pressure cuff.
  
  Observation/compound-numeric-blood-pressure-no-mean:
    name: Compound numeric observation with one component value absent
    description: This example is from a Blood Pressure cuff with one missing component.
  
  Observation/compound-observation-glucose:
    name: Compound observation with glucose and context
    description: This artificial example combines a glucose measurement and context information.
  
  Observation/stringenum-1234:
    name: String measurement example 1
    description: This example observation reports some arbitrary text from a cardiovascular fitness device.

  Observation/string-observation-1:
    name: String measurement example 2
    description: This example observation reports some arbitrary text from a Glucose meter explaining the failure of the measurement.
  
  Observation/coin-20181119202022:
    name: Coincident Timestamp with the gateway better synchronized then the
    description: This example is a Coincident Timestamp where the PHG is better synchronized to NTP time than the PHD.
  
  Observation/coin-example-timefault:
    name: Coincident Timestamp with a Time Fault
    description: This example is a Coincident Timestamp where the PHD has a time fault; it's current timeline is unknown and it reported timestamps in its measurements.
  
  Observation/coin-20181119174911:
    name: Coincident Timestamp from a BP device
    description: This Coincident Timestamp observation is referenced by the Blood Pressure Observation
  
  Observation/coin-example-1:
    name: Another Coincident Timestamp example
    description: This Coincident Timestamp observation is referenced by other Observation examples.

# Resource grouping for organized artifact list
groups:
  ObservationProfiles:
    name: Observation Profiles
    description: Profiles for different types of observations from personal health devices
    resources:
      - StructureDefinition/PhdBaseObservation
      - StructureDefinition/PhdNumericObservation
      - StructureDefinition/PhdCompoundObservation
      - StructureDefinition/PhdCompoundNumericObservation
      - StructureDefinition/PhdCodedEnumerationObservation
      - StructureDefinition/PhdBitsEnumerationObservation
      - StructureDefinition/PhdRtsaObservation
      - StructureDefinition/PhdStringObservation
      - StructureDefinition/PhdCoincidentTimeStampObservation

  DeviceProfiles:
    name: Device Profiles
    description: Profiles for personal health devices and gateways
    resources:
      - StructureDefinition/PhdDevice
      - StructureDefinition/PhdDeviceMetric
      - StructureDefinition/PhgDevice

  PatientProfile:
    name: Patient Profile
    description: Profile for patients using personal health devices
    resources:
      - StructureDefinition/PhdPatient

  Extensions:
    name: Extensions
    description: Extensions used by the PHD profiles
    resources:
      - StructureDefinition/Accuracy
      - StructureDefinition/Confidence95
      - StructureDefinition/SimpleAlerting

  Terminology:
    name: Terminology
    description: Code systems and value sets for personal health device data
    resources:
      - CodeSystem/ContinuaDeviceIdentifiers
      - CodeSystem/SimpleAlertOperationalStatesCS
      - CodeSystem/ASN1ToHL7
      - CodeSystem/ContinuaHFS
      - CodeSystem/ContinuaPHDInterfaceIDs
      - CodeSystem/PhdObservationCategories
      - ValueSet/MDCValueSet
      - ValueSet/MDCnotObject
      - ValueSet/ASN1DeviceBits
      - ValueSet/ASN1MeasurementBits
      - ValueSet/DeviceTypes11073MDC
      - ValueSet/SimpleAlertOperationalStates
      - ValueSet/MDCobject

  Capability:
    name: Capability Statement
    description: Server capability requirements
    resources:
      - CapabilityStatement/PhdFHIRServer

  ExampleBundles:
    name: Example Bundles
    description: Complete transaction examples
    resources:
      - Bundle/bundle-example-1
      - Bundle/bundle-continuousnonin

  ExampleDevices:
    name: Example Devices
    description: Device and gateway examples
    resources:
      - Device/phd-74E8FFFEFF051C00.001C05FFE874
      - Device/phd-711000FEFF5F49B0.B0495F001071
      - Device/phd-00601900010E9234.F45EABA80832
      - Device/phg-ecde3d4e58532d31.000000000000
      - Device/phg-example
      - DeviceMetric/bp-devicemetric-example

  ExamplePatients:
    name: Example Patients
    description: Patient examples
    resources:
      - Patient/patientExample-1
      - Patient/patientExample-2

  ExampleObservations:
    name: Example Observations
    description: Various observation examples from different device types
    resources:
      - Observation/numeric-spotnumeric
      - Observation/numeric-spo2-alarm
      - Observation/temperature-observation
      - Observation/glucose-observation
      - Observation/numeric-observation-not-a-number
      - Observation/rtsa-example
      - Observation/rtsa-example-2
      - Observation/meal-context-observation
      - Observation/bits-observation
      - Observation/bpm-status
      - Observation/compound-numeric-blood-pressure
      - Observation/compound-numeric-blood-pressure-no-mean
      - Observation/compound-observation-glucose
      - Observation/stringenum-1234
      - Observation/string-observation-1
      - Observation/coin-20181119202022
      - Observation/coin-example-timefault
      - Observation/coin-20181119174911
      - Observation/coin-example-1

# Page structure
pages:
  index.md:
    title: Personal Health Device Implementation Guide Home Page
    UseCases.md:
      title: Use Cases
    ProfilesOverview.md:
      title: Profiles Overview
    Organizations.md:
      title: Organizations
    Glossary.md:
      title: Glossary
  ProfileConsumers.md:
    title: Consuming the PHD Profile FHIR Resources
  TechnicalImplementationGuidance.md:
    title: PHG Implementation Guidance
    RemotePatientMonitoringConsiderations.md:
      title: Remote Patient Monitoring Considerations
    GenericModel.md:
      title: Generic and Extensible Model
    DIMtoFHIRMapping.md:
      title: DIM to FHIR Mapping
      FLOATS.md:
        title: IEEE 11073 FLOATs and SFLOATs
      Nomenclaturecodes.md:
        title: IEEE 11073-10101 MDC Nomenclature codes
      GeneratingtheTimeStampPartIdentifier.md:
        title: Generating the PHD Reported Timestamp Identifier
    Non11073PHDDevices.md:
      title: Non IEEE 11073 PHD Devices
  changes.md:
    title: Change Log
  Appendix.md:
    title: Appendix

# Additional parameters
parameters:
  shownav: true
  # fhir-extensions-path: "https://hl7.org/fhir/extensions/5.3.0-ballot-tc1/"


