// ============================================================
// Profile: PhdDeviceAlert
// ============================================================

Profile: PhdDeviceAlert
Parent: DeviceAlert
Id: PhdDeviceAlert
Title: "PhdDeviceAlert"
Description: "Profile for device alert that capture alert conditions from personal health devices."
//* ^meta.lastUpdated = "2026-02-13T00:00:00.000-05:00"
* ^url = "http://hl7.org/fhir/uv/phd/StructureDefinition/PhdDeviceAlert"
//* ^date = "2026-02-13T00:00:00.000-05:00"
* ^abstract = false

// ------------------------------------------------------------
// Alert Type
// ------------------------------------------------------------
//* code from http://hl7.org/fhir/ValueSet/devicealert-condition (required) // for 6.0.0-ballot4 or later
* condition.code from http://hl7.org/fhir/ValueSet/devicealert-condition (required) // for 6.0.0-ballot3
  * ^short = "Code for the alert condition"
  * ^definition = "MDC nomenclature code from partition 3 indicating the alert condition being reported"
  * ^comment = "The code identifies the specific alert condition from the IEEE 11073 medical device communication nomenclature."

// ------------------------------------------------------------
// Alert Label/Notification Text
// ------------------------------------------------------------
* label 0..1
  * ^short = "Threshold notification text"
  * ^definition = "Notification message displayed when the threshold is crossed."

// ------------------------------------------------------------
// Signal - for operational state and text
// ------------------------------------------------------------
* signal ^slicing.discriminator[0].type = #value
  * ^slicing.discriminator[=].path = "type"
  * ^slicing.rules = #open
// ------------------------------------------------------------
// derivedFrom: Link to source observations
// ------------------------------------------------------------
* derivedFrom 1..*
  * ^short = "Reference to the observation(s) this alert is associated with"
  * ^definition = "References to the PhdNumericObservation, PhdCompoundNumericObservation, PhdCompoundObservation, or other observations that this alert condition is derived from or associated with."
  * ^comment = "The alert is now represented as a separate resource that references the source measurement observation(s) via derivedFrom. The component element can be used to identify a specific component in case of an alert on a compound observation, e.g. on systolic blood pressure in a blood pressure observation."
// * derivedFrom.observation only Reference(PhdNumericObservation or PhdCompoundNumericObservation or PhdCompoundObservation) // for 6.0.0-ballot4 or later
* derivedFrom only Reference(PhdNumericObservation or PhdCompoundNumericObservation or PhdCompoundObservation) // for 6.0.0-ballot3

// ------------------------------------------------------------
// Mapping
// ------------------------------------------------------------
Mapping: IEEE-11073-10206-PhdDeviceAlert
Id: IEEE-11073-10206-PhdDeviceAlert
Title: "IEEE-11073-10206 ACOM Alert to FHIR"
Source: PhdDeviceAlert
* -> "Generated by gateway from an ACOM Observation with a Threshold Error status code"
//* code -> "MDC code from partition 3 indicating the alert condition being reported as selected by the gateway" // for 6.0.0-ballot4 or later
* condition.code -> "MDC code from partition 3 indicating the alert condition being reported as selected by the gateway" // for 6.0.0-ballot3
* signal -> "actual signal(s) from the gateway, if any, that triggered the alert"
* label -> "Text message displayed by the gateway when the threshold is crossed"
* derivedFrom -> "the Observation(s) with the Threshold error status code that triggered generation of the alert"
// Note: limit element is not reported by ACOM (IEEE 11073-10206); populated by PHG from device configuration or local settings